### PR TITLE
Fix/andriod 14

### PR DESCRIPTION
**Pull request by mzbyszynski**
DO NOT MERGE. WE KEEP THIS PR OPEN FOREVER.

Revisit this PR once we update to newer Notifee version.

### Fixes:
* Pulled in this [approved notifee pr](https://github.com/invertase/notifee/pull/1050)
* Updated some android code to match what is currently in notifee to resolve some build runtime errors.

### Checklist:
- [x] Build `yarn` then `yarn build:all` (Already done in this PR (https://github.com/rune/notifee/pull/3/commits/200d6979a6dbb3fff169054bf9cdfb9a0d87df8a)
- [x] Use `https://gitpkg.now.sh/rune/notifee/packages/react-native?COMMIT_HASH` in `package.json`

### CODE REVIEW

**Review by OlDirtyLam — APPROVED** [review]
very nice 👏

**Review by OlDirtyLam — APPROVED** [review]

**Comment by mieszko4** [comment]
> * Build `yarn` then `yarn build:all` (Already done in this PR ([200d697](https://github.com/rune/notifee/commit/200d6979a6dbb3fff169054bf9cdfb9a0d87df8a))

1. This points to another PR. I assume you meant to use https://github.com/rune/notifee/pull/5/commits/80b8d2790e48ed2a8fa9c7688c1468d7036aabe2?

2. There is a mixture of commits with `dist` and non-`dist` changes so it is hard to see what actual changes came after applying https://github.com/invertase/notifee/pull/1050

3. It is not clear what version of Notifee we are patching

3. Why is https://github.com/rune/notifee/pull/5/commits/6945232935b2990b7dd06974515b874b2cb39465 needed?

**Comment by mzbyszynski** [comment]
> * This points to another PR. I assume you meant to use [80b8d27](https://github.com/rune/notifee/commit/80b8d2790e48ed2a8fa9c7688c1468d7036aabe2)?

Actually this was just a copy-paste mistake. I copied those steps from your last pr.

> * There is a mixture of commits with `dist` and non-`dist` changes so it is hard to see what actual changes came after applying [feat: allow adding foreground service types dynamically invertase/notifee#1050](https://github.com/invertase/notifee/pull/1050)

I agree! It sucks

> * It is not clear what version of Notifee we are patching

I agree! I think once Notifee merges that pr or otherwise fixes the android 14 issue we should try to move back to their official verison.

> * Why is [6945232](https://github.com/rune/notifee/commit/6945232935b2990b7dd06974515b874b2cb39465) needed?

That was in the pr I merged in, but I couldn't see a reason for it and the app store wanted us to add a policy justification for it. I made a [comment](https://github.com/invertase/notifee/pull/1050/files#r1752070641) on the original pr about it

**Comment by mieszko4** [comment]
> I agree! I think once Notifee merges that pr or otherwise fixes the android 14 issue we should try to move back to their official verison.

Ok, but we think the patch is over the newest Notifee, right? I am just concerned if all fixes in https://github.com/rune/notifee/pull/3 are applied here. But maybe those fixes won't matter anymore in this PR.

**Comment by mzbyszynski** [comment]
> > I agree! I think once Notifee merges that pr or otherwise fixes the android 14 issue we should try to move back to their official verison.
> 
> Ok, but we think the patch is over the newest Notifee, right? I am just concerned if all fixes in #3 are applied here. But maybe those fixes won't matter anymore in this PR.

I did branch this from that pr branch

**Comment by mzbyszynski** [comment]
I think we were already using the commits from that pr in TinCan? Or was that a mistake

**Comment by mieszko4** [comment]
> I think we were already using the commits from that pr in TinCan? Or was that a mistake

We are, but I think that the following is still not in the newest Notifee? At least it was not when I created https://github.com/rune/notifee/pull/3. Not sure if it is still relevant though.
> fix: always use startService: not in original lib yet (https://github.com/rune/notifee/commit/c05c7ca3856e79a32a6b65d141806211cd340ed5)

**Comment by mzbyszynski** [comment]
I also just took another look at the notifee pr that I pulled the code from and that is not actually approved by any notifee maintainers, just some random person clicked approved I think 😞

**Comment by mieszko4** [comment]
> I also just took another look at the notifee pr that I pulled the code from and that is not actually approved by any notifee maintainers, just some random person clicked approved I think 😞

It is merged and released in 9.0.0 :)

**Comment by mzbyszynski** [comment]
Can be closed now that TinCan is back on main notifee branch

**Pull request closed without merging**
